
services:
  mongodb:
    image: mongo:7
    container_name: binitech-pdv-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=binitech_pdv

  rabbitmq:
    image: rabbitmq:3-management
    container_name: binitech-pdv-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  mongo_data:

