spring:
  application:
    name: BiniTech PDV
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: binitech_pdv

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 8.2.5

server:
  port: ${PORT:8080}

jwt:
  secret: ${JWT_SECRET:}
  access-expiration: ${JWT_ACCESS_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}

admin:
  username: ${ADMIN_USERNAME}
  password: ${ADMIN_PASSWORD}

security:
  pepper: ${SECURITY_PEPPER}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method